export default [
{task: 'Fazer algo', done: false},
{task: 'Fazer denovo', done: true},
{task: 'Fazer olha', done: false},
{task: 'Fazer algo', done: false},
{task: 'Fazer denovo', done: true},
{task: 'Fazer olha', done: false},
{task: 'Fazer algo', done: false},
{task: 'Fazer denovo', done: true},
{task: 'Fazer olha', done: false},
{task: 'Fazer algo', done: false},
{task: 'Fazer denovo', done: true},
{task: 'Fazer olha', done: false},
{task: 'Fazer algo', done: false},
{task: 'Fazer denovo', done: true},
{task: 'Fazer olha', done: false},
]